package com.interpreter.iroh;

enum TokenType {
	LEFT_PARENT,RIGHT_PARENT,LEFT_BRACE,RIGHT_BRACE,
	COMMA,DOT,MINUS,PLUS,SEMICOLON,SLASH,STAR,COLON,QUESTION,LEFT_BRAK,RIGHT_BRAK,

	BANG, BANG_EQUAL,EQUAL,EQUAL_EQUAL,GREATER,GREATER_EQUAL,
	LESS,LESS_EQUAL,
	IDENTIFIER,STRING,NUMBER,

	AND,LEAF,ELSE,FALSE,CRAFT,FOR,IF,EMPTY,OR,SERVE,OFFER,ELDER,STEM,TRUE,BREW,WHILE,BREAK,CONTINUE,SWITCH,CASE,DEFAULT,

	EOF

}
